### ISSUE TITLE
compatibility with newest epistasis and gpmap packages?

### ISSUE THREAD

**Issue by tylernstarr** [harmslab/notebooks-nonlinear-high-order-epistasis#2]
I'm trying to run these notebooks to learn how to implement these models. I downloaded and installed the newest versions of the gpmap and epistasis packages (12 Sept 2017), to make sure everything is up-to-date. In my Terminal:

git clone https://github.com/harmslab/epistasis
cd epistasis
pip install -e .

cd ..

git clone https://github.com/harmslab/gpmap
cd gpmap
pip install -e .

cd ..

git clone https://github.com/harmslab/notebooks-nonlinear-high-order-epistasis

I then launched Jupyter (4.3.1, running Python 3) in my browser via Anaconda (1.6.4), and have encountered errors that seem to stem from the source code when I try to execute the analyses. For example, with the figure-05 notebook, when I execute the second cell I get an error: "AttributeError: type object 'EpistasisPowerTransform' has no attribute 'from_json'". When I look into the power.py script, this seems correct that there is no from_json attribute that is described (assuming this is where it would be?)

**Comment by Zsailer** [comment]
Hey @tylernstarr 

Thanks for pointing this out. The `epistasis` and `gpmap` libraries have advanced quite a bit since we first published these notebooks. 

I'm updating these notebooks now (I'll ping you here when I finish).  I won't change any results, just fix the syntax to work with the new libraries. This should only take an hour or so.

If you want to run them sooner, you can always backport to the old releases of `epistasis` and `gpmap` libraries. The correct versions are listed in the README of this repo.

**Comment by Zsailer** [comment]
Hey @tylernstarr

I've updated the notebooks. They should be compatible with the most recent version of epistasis+gpmap. 

First, update your `epistasis` library, as I fixed some critical bugs. To do this, `cd` into the epistasis clone and run `git pull origin master`

Then, go ahead and pull the changes in these notebooks. 

Let me know if you still have issues!

**Comment by tylernstarr** [comment]
Thanks @Zsailer, it's working great now!

**Comment by Zsailer** [comment]
Awesome! If you have any questions about the actual code, feel free to bug me on the [epistasis gitter](https://gitter.im/harmslab/epistasis) (a chatroom for the project). The tutorials/docs still need a lot of work, so it may be easier to ask questions there.
